name: Build, Test, and Upload Artifacts

on:
  push:
    branches:
      - main
      - gh-action
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install nbconvert
      run: |
          pip install nbconvert ipython
  
    - name: Convert Notebooks to Python Scripts
      run: |
        mkdir -p test
        for notebook in examples/*.ipynb; do
          jupyter nbconvert --to script "$notebook" --output-dir=test
        done

    - name: Build package
      run: |
        pip install .

    - name: Run tests
      run: |
        mkdir -p test/figs
        cd test
        for script in ./*.py; do
          python "$script" 
        done
        mv *.png figs/

    - name: Upload test/figs as artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: test-figures
        path: test/figs/*
